table_info = {
    "items": {
        "description": "Table of products/items with detailed information",
        "columns": {
            "id": "Unique product identifier",
            "code": "Unique product code",
            "name": "Product name",
            "description": "Detailed product description",
            "category_id": "Category ID",
            "brand_id": "Brand ID (references brands.id)",
            "unit_id": "Measurement unit ID",
            "barcode": "Barcode",
            "codefournisseur": "Supplier code",
            "cost_price": "Purchase price / cost",
            "sale_price": "Selling price",
            "tva_group_id": "VAT group ID",
            "stock_min": "Recommended minimum stock",
            "stock_max": "Recommended maximum stock",
            "store_id": "Store ID (references stores.id)",
            "location": "Physical location",
            "is_active": "Active product (1) or inactive (0)",
            "created_at": "Creation date",
            "updated_at": "Last modification date",
        },
    },
    "stocks": {
        "description": "Table of current stock quantities per store",
        "columns": {
            "id": "Unique identifier",
            "item_id": "Product ID (references items.id)",
            "store_id": "Store ID (references stores.id)",
            "quantity": "Current stock quantity",
            "min_quantity": "Minimum threshold for this store",
            "max_quantity": "Maximum threshold for this store",
            "created_at": "Creation date",
            "updated_at": "Last modification date",
        },
    },
    "stock_movements": {
        "description": "History of all stock movements (inbound/outbound)",
        "columns": {
            "id": "Unique movement identifier",
            "item_id": "ID of the product concerned (references items.id)",
            "store_id": "ID of the store concerned (references stores.id)",
            "quantity": "Quantity (positive=inbound, negative=outbound)",
            "cost_price": "Unit price at the time of movement",
            "supplier_name": "Supplier name",
            "type": "Movement type: 'achat','ajustement','inventaire','retour_achat','vente'",
            "reference": "Document reference (invoice, slip, etc.)",
            "note": "Additional notes",
            "created_at": "Movement date",
            "updated_at": "Modification date",
        },
    },
    "brands": {
        "description": "Table of product brands/manufacturers",
        "columns": {
            "id": "Unique brand identifier",
            "name": "Brand name (unique)",
            "created_at": "Creation date",
            "updated_at": "Last modification date",
        },
    },
    "stores": {
        "description": "Table of stores/warehouses",
        "columns": {
            "id": "Unique store identifier",
            "name": "Store name",
            "description": "Store description",
            "created_at": "Creation date",
            "updated_at": "Last modification date",
        },
    },
    "delivery_notes": {
        "description": "Table of delivery notes / delivered orders",
        "columns": {
            "id": "Unique delivery note identifier",
            "sales_order_id": "Associated sales order ID",
            "numclient": "Customer number",
            "delivery_date": "Delivery date",
            "status": "Delivery status (en_cours, etc.)",
            "total_delivered": "Total quantity delivered",
            "total_ht": "Total excluding tax",
            "total_ttc": "Total including tax",
            "tva_rate": "Applied VAT rate",
            "notes": "Delivery notes",
            "numdoc": "Unique document number",
            "created_at": "Creation date",
            "updated_at": "Modification date",
        },
    },
    "delivery_note_lines": {
        "description": "Detailed lines of delivery notes (delivered products)",
        "columns": {
            "id": "Unique line identifier",
            "delivery_note_id": "Delivery note ID (references delivery_notes.id)",
            "article_code": "Code of the delivered item (references items.code)",
            "delivered_quantity": "Quantity delivered",
            "unit_price_ht": "Unit price excluding tax",
            "unit_price_ttc": "Unit price including tax",
            "remise": "Applied discount percentage",
            "total_ligne_ht": "Line total excluding tax",
            "total_ligne_ttc": "Line total including tax",
            "created_at": "Creation date",
            "updated_at": "Modification date",
        },
    },
}
